---
- name: create ansible default folder structure
  hosts: localhost
  gather_facts: true
 

  tasks:
  - name: install required packages
    ansible.builtin.yum:
      name: "{{yum_ansible_packages}}"
      state: latest
    become: true
  
  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest
    become: true

  - name: "create ansible folder for org {{org_name}}"
    ansible.builtin.file:
      state: directory
      path: "/{{org_name}}-ansible"
      owner: "{{ansible_user}}"
      mode: "0755"
    become: true
  
  - name: "create ansible inventory folder for org {{org_name}}"
    ansible.builtin.file:
      state: directory
      path: "/{{org_name}}-inventory"
      owner: "{{ansible_user}}"
      mode: "0700"
    become: true

  - name: configure sudoers file add nopasswd for user 
    ansible.builtin.lineinfile:
      # path: ~/test_sudoers
      path: /etc/sudoers
      state: present
      regexp: '^{{ansible_user}} ALL\s'
      line: '{{ansible_user}} ALL=(ALL) NOPASSWD: ALL'
    become: true

  - name: configure sudoers file - add requiretty'
    ansible.builtin.lineinfile:
      # path: ~/test_sudoers
      path: /etc/sudoers
      state: present
      regexp: '^Defaults:{{ansible_user}} !requiretty\s'
      line: 'Defaults:{{ansible_user}} requiretty'
    become: true

  - name: "copy ansible.cfg"
    ansible.builtin.copy:
      src: ansible.cfg
      dest: /etc/ansible/ansible.cfg
      owner: ansible
      mode: 0644
    become: true

  # - name: "set vault file var in ansible.cfg"
  #   ansible.builtin.lineinfile:
  #     # path: ~/test_sudoers
  #     path: /etc/ansible/ansible.cfg
  #     state: present
  #     regexp: '^vault_password_file=/{{org_name}}-inventory/.vaultpw\s'
  #     line: 'vault_password_file=/{{org_name}}-inventory/.vaultpw'
  #   become: true
  - name: "set vault file in ansible.cfg with ini"
    ansible.builtin.ini_file:
      path: /etc/ansible/ansible.cfg
      section: defaults
      option: vault_password_file
      value: "{{org_name}}-inventory/.vaultpw"

  - name: "create ansible inventory group vars for org {{org_name}}"
    ansible.builtin.file:
      state: directory
      path: "/{{org_name}}-inventory/group_vars"
      

  - name: "create group-vars for windows server"
    ansible.builtin.file:
      path: "/{{org_name}}-inventory/group_vars/windows_server.yaml"
      state: touch
  
  - name: "add line to var"
    ansible.builtin.blockinfile:
      # path: ~/test_sudoers
      path: "/{{org_name}}-inventory/group_vars/windows_server.yaml"
      append_newline: true
      prepend_newline: true
      block: |
        Match User ansible-agent
        PasswordAuthentication no
        ansible_user: Administrator
        ansible_password: Pa$$w0rd

# TODO:
# - create group vars and encrypt
# - create vault file?
# install pywinrm
# install win collection ansible-galaxy collection install ansible.windows