---
- name: create ansible default folder structure
  hosts: localhost
  gather_facts: true
 

  tasks:
  - name: install required packages
    ansible.builtin.yum:
      name: "{{yum_ansible_packages}}"
      state: latest
    become: true
  
  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest
    become: true

  - name: "create ansible folder for org {{org_name}}"
    ansible.builtin.file:
      state: directory
      path: "/{{org_name}}-ansible"
      owner: "{{ansible_user}}"
      mode: "0755"
    become: true
  
  - name: "create ansible inventory folder for org {{org_name}}"
    ansible.builtin.file:
      state: directory
      path: "/{{org_name}}-inventory"
      owner: "{{ansible_user}}"
      mode: "0700"
    become: true

  - name: configure sudoers file add nopasswd for user 
    ansible.builtin.lineinfile:
      # path: ~/test_sudoers
      path: /etc/sudoers
      state: present
      regexp: '^{{ansible_user}} ALL\s'
      line: '{{ansible_user}} ALL=(ALL) NOPASSWD: ALL'
    become: true

  - name: configure sudoers file - add requiretty'
    ansible.builtin.lineinfile:
      # path: ~/test_sudoers
      path: /etc/sudoers
      state: present
      regexp: '^Defaults:{{ansible_user}} !requiretty\s'
      line: 'Defaults:{{ansible_user}} requiretty'
    become: true

  - name: "copy ansible.cfg"
    ansible.builtin.copy:
      src: ansible.cfg
      dest: /etc/ansible/ansible.cfg
      owner: ansible
      mode: 0644
    become: true

# TODO:
# - create group vars and encrypt
# - create vault file?